import type { Metadata } from "next";
import { DM_Serif_Text } from "next/font/google";
import localFont from "next/font/local";
import "./globals.css";

const dmSerifText = DM_Serif_Text({
  variable: "--font-serif",
  subsets: ["latin"],
  weight: ["400"],
  style: ["normal", "italic"],
});

const modernNegra = localFont({
  src: "../public/fonts/Modern Negra Demo.ttf",
  variable: "--font-modern-negra",
  fallback: ["serif"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${dmSerifText.variable} ${modernNegra.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
